<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE films [

        <!ELEMENT films (film)+>
        <!ELEMENT film (titel, hoofdrolspeler, jaartal, categorie, land)>


        <!ELEMENT titel (#PCDATA)>
        <!ELEMENT hoofdrolspeler (#PCDATA)>
        <!ELEMENT jaartal (#PCDATA)>

        <!ATTLIST film categorie #IMPLIED>
        <!ATTLIST film land #DEFAULT "BelgiÃ«>


        ]>


<films>
    <film>
        <titel>Rambo</titel>
        <hoofdrolspeler>Sylvester Stallone</hoofdrolspeler>
        <jaartal>1985</jaartal>
    </film>
    <film>
        <titel>Robocop</titel>
        <hoofdrolspeler>Een zeer goed acteur</hoofdrolspeler>
        <jaartal>1985</jaartal>

    </film>
    <film>
        <titel>Jurrassic Park</titel>
        <hoofdrolspeler>Steven Spielberg</hoofdrolspeler>
        <jaartal>1995</jaartal>

    </film>
    <film>
        <titel>2001: A Space Odyssey</titel>
        <hoofdrolspeler>Stanley Kubrick</hoofdrolspeler>
        <jaartal>1980</jaartal>

    </film>
    <film>
        <titel>E.T.</titel>
        <hoofdrolspeler>Steven Spielberg</hoofdrolspeler>
        <jaartal>1990</jaartal>

    </film>
</films>

