=== VincentBott/OefeningenXML/src/com/company/SchemaOef3.xsd
<xs:schema xmlns="http://beta.ua.ac.be/boeken" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://beta.ua.ac.be/boeken"
           elementFormDefault="qualified" attributeFormDefault="unqualified">


    <xs:element name="boeken">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="boek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titel" minLength=">=1" maxOccurs="unbounded"/>
                            <xs:element name="auteur" type="xs:string" minOccurs="0" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>

                                        </xs:sequence>
                                    </xs:complexType>
                            </xs:element>
                            <xs:element name="jaartal"  default="2000" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="beoordeling"  minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== VincentBott/OefeningenXML/src/com/company/SchemaOef3.xml
<?xml version="1.0" encoding="UTF-8"?>


<boeken xmlns="http://beta.ua.ac.be/boeken" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://beta.ua.ac.be/boeken SchemaOef3.xsd">

    <boek>
        <titel>Das Kapital</titel>
        <auteur>Karl Marx</auteur>
        <jaartal>1880</jaartal>
        <beoordeling>Heel goed</beoordeling>
    </boek>
    <boek>
        <titel>On the road</titel>
        <auteur>Jack Kerouac</auteur>
        <jaartal>1960</jaartal>
        <beoordeling>Heel goed</beoordeling>
    </boek>
    <boek>
        <titel>De bijbel</titel>
        <auteur>Jezus Christus</auteur>
        <jaartal>100</jaartal>
        <beoordeling>Slecht</beoordeling>
    </boek>
    <boek>
        <titel>Also sprach Zarathustra</titel>
        <auteur>Friedrich Nietzsche</auteur>
        <jaartal>1860</jaartal>
        <beoordeling>Goed</beoordeling>
    </boek>

</boeken>


<!--
Een jaartal (wanneer het niet ingevuld is, moet het de waarde “2000” hebben)
Een titel (moet minstens 1 karakter lang zijn)
Een beoordeling (je moet kunnen meegeven of het boek slecht, goed of heel goed is)
Eén of meerdere auteurs (elke auteur moet minstens 1 karakter lang zijn). Je moet voor
elke auteur ook kunnen bijhouden of het een man of een vrouw is. Het geslacht moet verplicht
worden ingevuld, maar je mag geen default waarde voorzien
-->
