=== VincentBott/OefeningenXML/src/com/company/SchemaOef2.xsd
<xs:schema xmlns="http://www.beta.ua.ac.be" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.beta.ua.ac.be"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="producten">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titel" maxOccurs="unbounded">
                            <xs:element name="auteur" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="prijs" type="valutaType" minOccurs="0" maxOccurs="unbounded"/>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="valutaType">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="valuta" use="required" default="EUR" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== VincentBott/OefeningenXML/src/com/company/SchemaOef2.xml
<?xml version="1.0" encoding="UTF-8"?>

<producten xmlns="http://www.beta.ua.ac.be" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.beta.ua.ac.be SchemaOef2.xsd">


    <product>
        <titel>XML family of specifications</titel>
        <auteur>Kenneth B. Sall</auteur>
        <prijs valuta="EUR">50.75</prijs>
    </product>
    <product>
        <titel>Professional XML</titel>
        <auteur>Mark Birbeck et al.</auteur>
        <prijs valuta="EUR">62.17</prijs>
    </product>
</producten>
