=== VincentBott/OefeningenXML/src/com/company/test.xsd
<?xml version="1.0" encoding="UTF-8" ?>


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns="http://www.vincentbott.org"
           targetNamespace="http://www.vincentbott.org">
    <xs:element name="namen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naam"  maxOccurs="10">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="voornaam" type="xs:string"/>
                        <xs:element name="achternaam" type="xs:string"/>
                        <xs:element name="geboortedatum" type="geboortedatumtype"/>
                    </xs:sequence>
                </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="geboortedatumtype">
        <xs:simpleContent>
            <xs:extension base="xs:date">
                <xs:attribute name="nationaliteit" use="required" fixed="B" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== VincentBott/OefeningenXML/src/com/company/test.xml
<?xml version="1.0" encoding="UTF-8" ?>

<namen xmlns="http://www.vincentbott.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

       xsi:schemaLocation="http://www.vincentbott.org  test.xsd">


    <naam>
        <voornaam>Vincent</voornaam>
        <achternaam>Bott</achternaam>
        <geboortedatum nationaliteit="B">1974-10-28</geboortedatum>

    </naam>
    <naam>
        <voornaam>Kristel</voornaam>
        <achternaam>Verbeke</achternaam>
        <geboortedatum nationaliteit="B">1974-10-28</geboortedatum>
    </naam>
    <naam>
        <voornaam>Kathleen</voornaam>
        <achternaam>Aerts</achternaam>
        <geboortedatum nationaliteit="B">1974-10-28</geboortedatum>
    </naam>
    <naam>
        <voornaam>Karent</voornaam>
        <achternaam>Damen</achternaam>
        <geboortedatum nationaliteit="B">1974-10-28</geboortedatum>
    </naam>
    <naam>
        <voornaam>Jef</voornaam>
        <achternaam>De Smedt</achternaam>
        <geboortedatum nationaliteit="B">1974-10-28</geboortedatum>
    </naam>

</namen>
